[tool.poetry]
name = "google-api"
version = "0.1.0"
description = ""
authors = ["tools1x <tools@1xpartner.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gspread-dataframe = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
